# Generated by Django 3.2.4 on 2021-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_auto_20210626_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
